<a href="https://colab.research.google.com/github/G100A008/-/blob/master/G100A008_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列

a                     #看a的內容

array([1, 2, 3])

In [ ]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列
b = np.array([3,2,0])

a * b                 #ab相乘

array([3, 4, 0])

In [16]:
np.arange(10)         #產生0~9的數值

array([0, 2, 4, 6, 8])

In [17]:
np.arange(0,10,2)     #(起始,終點,間距)

array([0, 2, 4, 6, 8])

In [26]:
np.linspace(0,10,15)  #包含終點共15個數,分成14份

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [32]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
c.shape               #2代表是二維陣列,3表示有3個元素

(2, 3)

In [40]:
c.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
c.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [36]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [37]:
d.shape

(1, 4, 3)