<a href="https://colab.research.google.com/github/G100A008/-/blob/master/G100A008_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列

a                     #看a的內容

array([1, 2, 3])

In [ ]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列
b = np.array([3,2,0])

a * b                 #ab相乘

array([3, 4, 0])

In [ ]:
np.arange(10)         #產生0~9的數值

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,10,2)     #(起始,終點,間距)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,10,15)  #包含終點共15個數,分成14份

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [3]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.ndim

2

In [4]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.shape

(2, 3)

In [5]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.size

6

In [9]:
import numpy as np

ar1=np.array([2,4,6,8]); 
ar1.dtype

dtype('int64')

In [27]:
import numpy as np
ar2=np.array([2,-1,6,3],dtype='float');
ar2
ar2.dtype

dtype('float64')

In [15]:
import numpy as np

ar3=np.array([2.,4,6,8]); 

ar3.dtype

dtype('float64')

In [19]:
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [20]:
intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [30]:
import numpy as np
np.random.seed(0) 

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))  