<a href="https://colab.research.google.com/github/G100A008/-/blob/master/G100A008_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列

a                     #看a的內容

array([1, 2, 3])

In [ ]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列
b = np.array([3,2,0])

a * b                 #ab相乘

array([3, 4, 0])

In [ ]:
np.arange(10)         #產生0~9的數值

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(0,10,2)     #(起始,終點,間距)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace(0,10,15)  #包含終點共15個數,分成14份

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [1]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.ndim

2

In [2]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.shape

(2, 3)

In [3]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.size

6

In [ ]:
import numpy as np

ar1=np.array([2,4,6,8]); 
ar1.dtype

dtype('int64')

In [ ]:
import numpy as np
ar2=np.array([2,-1,6,3],dtype='float');
ar2
ar2.dtype

dtype('float64')

In [ ]:
import numpy as np

ar3=np.array([2.,4,6,8]); 

ar3.dtype

dtype('float64')

In [6]:
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [7]:
intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [4]:
import numpy as np
np.random.seed(0) 

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))  

In [5]:
import numpy as np
np.random.seed(0) 

x1 = np.random.randint(10, size=6) 
x2 = np.random.randint(10, size=(3, 4)) 
x3 = np.random.randint(10, size=(3, 4, 5))  

In [9]:
import numpy as np
z1 = np.zeros((2, 3))
z2 = np.ones((2, 3))
z1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
import numpy as np

ar9a = np.array([[ 1.,  0.,  0.],[ 0.,  1.,  0.],[ 0.,  0.,  1.]]);
ar9a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
import numpy as np

ar9b = np.eye(3);
ar9b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
import numpy as np

ar10=np.diag((2,1,4,6));
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [13]:
import numpy as np

ar12 = np.linspace(1., 4., 6) # start, end, num
ar12

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [14]:
import numpy as np

ar11=np.arange(2, 3, 0.1) # start, end, step
ar11

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [19]:
import numpy as np
arr = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [20]:
import numpy as np
arr = np.shape([range(i, i + 3) for i in [2, 4, 6]])
arr

(3, 3)

In [24]:
import numpy as np
arr = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr.ndim

2

In [25]:
import numpy as np
arr = np.array([range(i, i + 3) for i in [2, 4, 6]])
arr.dtype

dtype('int64')

In [26]:
import numpy as np

# x = np.arange(2,10)
x = np.arange(2,10).reshape(2,4)
y = np.arange(2,10).reshape(4,2)
x
y
#x.shape

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(10,15)]); 
ar
ar.ravel()
ar.T
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [28]:
np.tile(np.array([[1,2],[6,7]]),3)
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [30]:
import numpy as np
x = np.arange(2,10)
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x[0]

2

In [34]:
x[-1]

9

In [35]:
x[-2]

8

In [36]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]]); 
ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [37]:
ar[1,2]

13

In [38]:
ar[2,:]

array([11, 12, 13])

In [39]:
ar[:,1]

array([ 3,  8, 12])

In [40]:
ar[2,-1]

13

In [41]:
ar=2*np.arange(6); 
ar

array([ 0,  2,  4,  6,  8, 10])

In [42]:
ar[1:5:2]

array([2, 6])

In [43]:
ar[1:6:2]

array([ 2,  6, 10])

In [44]:
ar[:4]

array([0, 2, 4, 6])

In [45]:
ar[4:]

array([ 8, 10])

In [46]:
ar[::3]

array([0, 6])

In [47]:
ar[:3]=1;
ar

array([ 1,  1,  1,  6,  8, 10])

In [48]:
ar[2:]=np.ones(4);
ar

array([1, 1, 1, 1, 1, 1])

In [49]:
import numpy as np

ar=np.arange(1,5)
ar.prod()

24

In [50]:
import numpy as np
ar=np.array([np.arange(1,6),np.arange(1,6)]);
ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [51]:
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [52]:
np.prod(ar,axis=1)

array([120, 120])

In [54]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10]]); 
ar.sum()

54

In [55]:
ar.mean()

6.0

In [56]:
np.median(ar)

6.0

In [57]:
import numpy as np
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a + b

array([3., 4., 5.])

In [58]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [60]:
arr+arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [62]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [65]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [66]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [70]:
ar=np.array([[1,1],[1,1]]);
ar2=np.array([[2,2],[2,2]]);

ar*ar2 # 標準Array multiplication(矩陣相乘) 

array([[2, 2],
       [2, 2]])

In [71]:
ar.dot(ar2) # 內積運算

array([[4, 4],
       [4, 4]])

In [72]:
ar=range(1000)
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 5: 383 µs per loop


In [73]:
ar=np.arange(1000)
%timeit ar**3

The slowest run took 8.12 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.56 µs per loop


In [74]:
import numpy as np
arr = np.arange(10)
arr

np.sqrt(arr)

np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])