<a href="https://colab.research.google.com/github/G100A008/-/blob/master/G100A008_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列

a                     #看a的內容

array([1, 2, 3])

In [13]:
import numpy as np

a = np.array([1,2,3]) #用NumPy的的np.array()函數將將[1,2,3]的的list轉成陣列
b = np.array([3,2,0])

a * b                 #ab相乘

array([3, 4, 0])

In [3]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.ndim

2

In [ ]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.shape

(2, 3)

In [ ]:
import numpy as np

ar2=np.array([[0,3,5],[2,8,7]]) # 產生一個 2D array
ar2.size

6

In [ ]:
import numpy as np

ar1=np.array([2,4,6,8]); 
ar1.dtype

dtype('int64')

In [ ]:
import numpy as np

ar3=np.array([2.,4,6,8]); 

ar3.dtype

dtype('float64')

In [ ]:
f_ar = np.array([13,-3,8.88])
f_ar

array([13.  , -3.  ,  8.88])

In [ ]:
intf_ar=f_ar.astype(int)
intf_ar

array([13, -3,  8])

In [ ]:
import numpy as np

b = np.linspace(0, 2, 4)
b

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [ ]:
ar2=np.array([2,-1,6,3], dtype="float"); 
ar2
ar2.dtype

dtype('float64')

In [ ]:
import numpy as np
b=np.array([range(i,i+3)for i in [2,4,6]])
b 

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
ar=range(1000)
%timeit[ar[i]**3 for i in ar]

1000 loops, best of 5: 404 µs per loop


In [ ]:
ar=np.arange(1000)
%timeit ar**3

The slowest run took 41.42 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.62 µs per loop


In [ ]:
c = np.linspace(0, 2, 4, endpoint=False) 
c

array([0. , 0.5, 1. , 1.5])

In [ ]:
class C1: pass
z = C1()
z.x = 23
print(z.x)

23
